apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-stack-kube-prom-prometheus.default.svc.cluster.local:9090
        query: |
          sum(irate(
            nginx_ingress_controller_requests{ingress="rollouts-demo-stable", status!~"5.*"}[30s]
          )) /
          sum(irate(
            nginx_ingress_controller_requests{ingress="rollouts-demo-stable"}[30s]
          ))
